"""empty message

Revision ID: 5c7fd6bd200f
Revises: 11931186e391
Create Date: 2020-06-04 09:18:34.142188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7fd6bd200f'
down_revision = '11931186e391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customer_phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_phone', sa.CHAR(length=15), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
