"""empty message

Revision ID: 64cde4228acf
Revises: 7f407e46e01c
Create Date: 2020-06-04 09:20:56.002084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cde4228acf'
down_revision = '7f407e46e01c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipped')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipped', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
