"""empty message

Revision ID: 7f407e46e01c
Revises: 5c7fd6bd200f
Create Date: 2020-06-04 09:18:49.985512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f407e46e01c'
down_revision = '5c7fd6bd200f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_phone', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customer_phone')
    # ### end Alembic commands ###
