"""empty message

Revision ID: e1494e50506e
Revises: 64cde4228acf
Create Date: 2020-06-04 09:21:06.052254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1494e50506e'
down_revision = '64cde4228acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipped')
    # ### end Alembic commands ###
